### ISSUE TITLE
[Taxonomy Tree]:   `Candy & Chocolate ` should have a `flavor` attribute

### ISSUE THREAD

**Issue by filiphsps** [Shopify/product-taxonomy#313]
### Taxonomy Field

Attributes

### Vertical

Food, Beverages & Tobacco

### Change Type

Assign attribute to more categories

### Issue

the attribute `flavor (gid://shopify/TaxonomyAttribute/1458)` is available on both snacks/chips and cookies but is absent on `Candy & Chocolate`.

### Description

Add the attribute `gid://shopify/TaxonomyAttribute/1458` to the category `gid://shopify/TaxonomyCategory/fb-2-3` and its children.

### Merchant Store

swedish-candy-store.com

**Comment by ornanatan** [comment]
Hey,

Thanks for reaching out, after reviewing your comments we will implement the changes in our next taxonomy release.
