### ISSUE TITLE
[Taxonomy Tree]:  Sporting Goods > Outdoor Recreation > Camping & Hiking > Camping Hammocks

### ISSUE THREAD

**Issue by wrewrite** [Shopify/product-taxonomy#324]
### Taxonomy Field

Categories

### Vertical

Sporting Goods

### Change Type

New category or attribute

### Issue

[Camping Hammocks] category is missing from Sporting Goods tree.

### Description

Hammocks are relegated to the Home and Garden branch but there is a notable and distinct market segment of Camping Hammocks that is adjacent to Tents and strictly belongs in Sporting Goods. In retail stores they are displayed alongside the tents; these are used in extreme environments instead of tents, but are not tents. There are many vendors and manufacturers. 

Missing Categories:
Sporting Goods > Outdoor Recreation > Camping & Hiking > Camping Hammocks
Sporting Goods > Outdoor Recreation > Camping & Hiking > Camping Hammocks > Camping Hammock Accessories

Attributes:
Fabric: gid://shopify/TaxonomyAttribute/2777
Color:  gid://shopify/TaxonomyAttribute/1 

### Merchant Store

https://hennessyhammock.com

**Comment by ricardotejedorsanz** [comment]
Thank you for your suggestions @wrewrite.
We're planning to implement these changes as part of our upcoming release.
You can track our progress here: https://github.com/Shopify/product-taxonomy/pull/379
