### ISSUE TITLE
[Localization Fix]: Dist localization files seems outdated?

### ISSUE THREAD

**Issue by mkromann** [Shopify/product-taxonomy#396]
### Are you reporting a Mixed Language Experience (MLX) or a Translation Quality issue?

None

### Target Language(s)

All languages

### Taxonomy Field

Other

### Issue

`dist/{lang}` seems outdated compared to the latest `en` data.

Example: `dist/da/mappings.json` uses an old input_taxonomy: `shopify/2024-04` compared to the latest `shopify/2024-10-unstable`.

### Description

Interesting project. 

I was looking for some Danish translations and noticed that the dist files seems outdated.

I couldn't immediately see why though.

**Comment by tylerrowsell** [comment]
Hey @mkromann the main branch of this repo is considered unstable. The translations are brought in through an asynchronous action. This results in the localizations being out of sync some times.

When a new version is cut all translations will be available in that version.
