### ISSUE TITLE
[Taxonomy Tree]: Missing from String Instruments

### ISSUE THREAD

**Issue by zumier** [Shopify/product-taxonomy#410]
### Taxonomy Field

Categories

### Vertical

Arts & Entertainment

### Change Type

New category or attribute

### Issue

Missing categories for Banjos, Mandolins, Ukuleles

### Description

Seems like these common instruments should have their own categories.

### Merchant Store

https://larkinthemorning.com

**Comment by ornanatan** [comment]
Hi,

Thank you so much for reaching out to us. We have reviewed your request and will add it to the next taxonomy edition.
