### ISSUE TITLE
[Taxonomy Tree]: Plated values missing for Jewelry material

### ISSUE THREAD

**Issue by anotherssa** [Shopify/product-taxonomy#411]
### Taxonomy Field

Values

### Vertical

Apparel & Accessories

### Change Type

New attribute value

### Issue

The taxonomy is missing suitable values for the plated jewelry materials (such as: gold plated, rose gold plated, white gold plated, silver plated, etc.), which are very common in jewelry.

### Description

While base materials like gold, silver, and platinum can describe such values, plated variants provide a more precise description and are very common in the jewelry industry.

**Comment by ornanatan** [comment]
Hi,

Thank you so much for reaching out, we will add these changes to our current release :-)
